---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: okta-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: okta-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: okta-operator-controller-manager
    namespace: {{ .Release.Namespace }}
