# permissions for end users to view oktaclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oktaclient-viewer-role
rules:
- apiGroups:
  - okta.jaconi.io
  resources:
  - oktaclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - okta.jaconi.io
  resources:
  - oktaclients/status
  verbs:
  - get
