# permissions for end users to edit oktaclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oktaclient-editor-role
rules:
- apiGroups:
  - okta.jaconi.io
  resources:
  - oktaclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - okta.jaconi.io
  resources:
  - oktaclients/status
  verbs:
  - get
