name: release

on:
  push:
    branches:
      - main

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Use a different token so subsequent workflows are executed.
          # See https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}

      - uses: freenet-actions/setup-yq@v2
        with:
          version: 4.27.2

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.0'
      - run: make test

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
