name: publish

on:
  release:
    types:
      - published

jobs:
  register:
    name: Package, Publish, and Register
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: go version
      - id: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: build-and-push
        run: make docker-build docker-push
        env:
          IMG: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}

  helm:
    name: Push Helm Chart
    runs-on: ubuntu-latest
    env:
      HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
      HELM_VERSION_TO_INSTALL: 3.9.0 # version of HEL to install
      GCR_IMAGE: ghcr.io/${{ github.repository }}-helm-chart

    steps:
      - uses: actions/checkout@v3

      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: login to ghcr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin

      - name: save helm chart to local registry
        run: |
          helm package ${{ github.workspace }}/helm/ ${{ env.GCR_IMAGE }}:${{ github.event.release.tag_name }}

      - name: publish chart to ghcr
        run: |
          helm push ${{ env.GCR_IMAGE }}:${{ github.event.release.tag_name }}
