name: publish

on:
  release:
    types:
      - published

jobs:
  register:
    name: Package, Publish, and Register
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}:latest

  helm:
    name: Push Helm Chart
    runs-on: ubuntu-latest
    env:
      HELM_VERSION_TO_INSTALL: 3.9.0 # version of HEL to install
      GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/helm-charts

    steps:
      - uses: actions/checkout@v4

      - name: install helm
        uses: Azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: login to ghcr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin

      - name: save helm chart to local registry
        run: |
          helm package ${{ github.workspace }}/helm/

      - name: publish chart to ghcr
        run: |
          export CHART_NAME=$(grep 'name:' ./helm/Chart.yaml | tail -n1 | awk '{ print $2 }')
          export CHART_VERSION=$(grep 'version:' ./helm/Chart.yaml | tail -n1 | awk '{ print $2 }')
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://${{ env.GCR_IMAGE }}
